### ISSUE TITLE
java.lang.NoClassDefFoundError: org/eclipse/microprofile/opentracing/tck/application/TestWebServicesApplication

### ISSUE THREAD

**Issue by fmhwong** [eclipse/microprofile-opentracing#142]
In release 1.3-RC1:

When running REST client TCK with Open Liberty, I got `java.lang.NoClassDefFoundError: org/eclipse/microprofile/opentracing/tck/application/TestWebServicesApplication`.  

`RestClientApplication` extends `TestWebServicesApplication`.  However, `TestWebServicesApplication` is deleted from the war file at this line.

https://github.com/eclipse/microprofile-opentracing/blob/85a2c99efbb61fb39f17f95d56de688cfc087f5c/tck/rest-client/src/main/java/org/eclipse/microprofile/opentracing/tck/rest/client/OpenTracingMpRestClientTests.java#L50

Adding a log from gitter
```
Tests run: 77, Failures: 1, Errors: 0, Skipped: 15, Time elapsed: 52.742 sec <<< FAILURE! - in TestSuite
arquillianBeforeClass(org.eclipse.microprofile.opentracing.tck.rest.client.OpenTracingMpRestClientTests)  Time elapsed: 4.085 sec  <<< FAILURE!
org.jboss.arquillian.container.spi.client.container.DeploymentException: Failed to deploy opentracing on OpentracingTCKServer: java.lang.NoClassDefFoundError: org/eclipse/microprofile/opentracing/tck/application/TestWebServicesApplication
    at io.openliberty.arquillian.managed.WLPManagedContainer.throwDeploymentException(WLPManagedContainer.java:1242)
    at io.openliberty.arquillian.managed.WLPManagedContainer.waitForApplicationTargetState(WLPManagedContainer.java:1003)
    at io.openliberty.arquillian.managed.WLPManagedContainer.deploy(WLPManagedContainer.java:449)
    at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$3.call(ContainerDeployController.java:161)
    at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$3.call(ContainerDeployController.java:128)
    at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.executeOperation(ContainerDeployController.java:271)
    at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.deploy(ContainerDeployController.java:127)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by pavolloffay** [comment]
hi @fmhwong I would not block the final release because of this issue. I got it successfully running in Smallrye https://github.com/smallrye/smallrye-opentracing/pull/28.

The fix would be pretty straight forward:
* `RestClientApplication` does not implement `TestWebServicesApplication`.
* add all necessary resources to `RestClientApplication`
* Move logic from `TestWebServicesApplication` to an utility class
